apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-nginx
  labels:
    app: alpine
spec:
  replicas: 15
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine
        image: alpine
        ports:
        - containerPort: 80
