apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
  namespace: default
  labels:
    app: alpine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine
        image: alpine
        ports:
        - containerPort: 8080
