name: baremetal kubernetes deployment
on:
  workflow_dispatch
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Copy single file to remote
      uses: garygrossgarten/github-action-scp@release
      with:
          local: test-deployment.yaml
          remote: /home/ubuntu
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey : ${{ secrets.SSH_PRIVATE_KEY }}
          
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: kubectl apply -f test-deployment.yaml
